### ISSUE TITLE
Norconex: WebDriverHttpFetcher HtmlUnit Driver Support

### ISSUE THREAD

**Issue by shiveendrasiingh** [Norconex/crawlers#1036]
Do you have support for htmlunit driver?
I was trying to find out the configuration for the same but not able to find it.
Is there anything I am missing.

**Comment by essiembre** [comment]
Hello @shiveendrasiingh, not sure if this reaches you too late, but out of the box support Chrome, Firefox, Edge, Safari and Opera are supported, no HtmlUnit.  

You may be able to trick it by any required dependencies to the crawler classpath (e.g., `lib` folder) and configure it by first chosing supported browser name, but overwriting all its property to rather match HtmlUnit.  

Something like this:

```xml
<fetcher class="WebDriverHttpFetcher">
   <!-- "browser" is required, but overwrite it by being explicit about other settings -->
   <browser>edge</browser>
   
   <browserPath>(HtmlUnit executable)</browserPath>
   <driverPath>(HtmlUnit WebDriver location)</driverPath>
   <capabilities>
     <capability name="..."><!-- anything required by HtmlUnit ---></capability>
   </capabilities>
```

You may be just fine with the above. if not, let us know and we can mark it as a feature request to support HtmlUnit.
