### ISSUE TITLE
I want to get the content Type (MIME type) for each crawled entry

### ISSUE THREAD

**Issue by HailunTan** [Norconex/crawlers#1038]
As the title suggested, I checked the Norconext crawler. There are only three data fields from the crawled entries:

1. URL reference
2. meta-data
3. content with the HTML stripped.

Could you please advise how I can get the content type of the crawled entry in Norconex crawler?
Thanks.

**Comment by essiembre** [comment]
Have you specified a "Committer"?   This is what's reponsible for sending all crawled data to a location of your choice.  You may want to start with storing crawled content on the local filesystem as a test while you familiarize yourself.  Like using the [XMLFileCommitter](https://opensource.norconex.com/committers/core/v3/apidocs/com/norconex/committer/core3/fs/impl/XMLFileCommitter.html).  File a full list of available committers here: https://opensource.norconex.com/committers/

You'll find in the generated output files that it contains the three items you are seeking (URL, metadata, and text-only content).

The content type may be present in a few different forms depending on the metadata available, but one that should always be there (unless you filtered it out intentionally) is `document.contentType`.  You may also like `document.contentFamily` which offers simple categorization of documents based on their type.
