### ISSUE TITLE
What can I do if I want to get the images(.jpg) from the sites? 

### ISSUE THREAD

**Issue by haolin96** [Norconex/crawlers#884]
What can I do if I want to get the images(.jpg) from the sites? Where to set the regular expression or others to get the link or the pictures from crawler?

**Comment by sakanaosama** [comment]
Hi, 
First of all, to include all the images (assuming excluding the other format) we use the Regex at"
"referenceFilters" Filters URLs BEFORE any download. e.g. only included HTML and jpg
"documentFilters" Filter documents, AFTER links were extracted e.g only included jpg


     <referenceFilters>
        <filter class="ExtensionReferenceFilter" onMatch="include">
          jpg,html
        </filter>
      </referenceFilters>










There are few options here:

**Comment by sakanaosama** [comment]
Hi,
You had three question there

1. Including Images from Fetch Using Regex:
To achieve this, you can utilize Regex within "referenceFilters" and "documentFilters". The former filters URLs before any download, while the latter filters documents after links extraction. For instance:

```
 <referenceFilters>
    <filter class="ExtensionReferenceFilter" onMatch="include">
      jpg,html
    </filter>
  </referenceFilters>
```
Refer to the documentation:
https://opensource.norconex.com/crawlers/core/v2/apidocs/com/norconex/collector/core/filter/impl/ExtensionReferenceFilter.html
https://opensource.norconex.com/crawlers/web/v3/configuration#metadataFilters

2. Obtaining Links Post-Crawling:
To extract links after crawling, you can employ FieldReportTagger to generate a report for all reference fields. Refer to the documentation for more details:

https://opensource.norconex.com/importer/v3/apidocs/com/norconex/importer/handler/tagger/impl/FieldReportTagger.html#nx-xml-usage-heading

3. Restoring the original fetched Images directly from the Crawler:
this isn't supported out of the box but you can achieve this by using ExternalTransformer. This allows manipulation of the original sources during the binary form, such as the original jpg. You'll need your own script to copy the original sources to a destination directory. Refer to the documentation for implementation details:

https://opensource.norconex.com/importer/v3/apidocs/com/norconex/importer/handler/transformer/impl/ExternalTransformer.html#nx-xml-usage-heading

**Comment by haolin96** [comment]
Very appreciate for your answer.
