### ISSUE TITLE
How to fetch a given set of files but NOT parse them in Norcornex web crawler?

### ISSUE THREAD

**Issue by HailunTan** [Norconex/crawlers#918]
Hi,

I wish to config Norcornex web crawler to fetch /download a given set of files, specified by their extension names. but I do not want these files to be parsed/extracted with the texts.

For example, I want  the crawler to  fetch all the (*.doc) files from a given web site but I DO NOT want the crawler to parse these doc files. Just downloaded them and placed them into a  given working directory.

The existing extensionReferenceFilter class can either be "included" (i.e., fetch and parse) or "excluded" (i.e., not fetch nor parse).  I am not sure how to make the files matching this filter to be fetched but NOT parsed? 

 How shall I config the crawler? Is  extensionReferenceFilter class the right one to follow for solution to this problem? Thanks.

**Comment by sakanaosama** [comment]
Hi
Assuming that the website you're referring to may contain various file types, please note that it may require HTML references to link to the document files themselves.

1. Including specific file types from the fetch:
To achieve this, you can utilize Regex within "referenceFilters" and "documentFilters". The former filters URLs before download, while the latter filters documents after link extraction. For instance:
```
 <referenceFilters>
    <filter class="ExtensionReferenceFilter" onMatch="include">
      html, doc
    </filter>
  </referenceFilters>
```
Refer to the documentation:
https://opensource.norconex.com/crawlers/core/v2/apidocs/com/norconex/collector/core/filter/impl/ExtensionReferenceFilter.html
https://opensource.norconex.com/crawlers/web/v3/configuration#metadataFilters

2. Saving the original fetched file directly from the Crawler:
Enable keepDownloads to keep downloaded files on local disk under <workDir>/downloads.
https://opensource.norconex.com/crawlers/web/v3/configuration#keepDownloads

**Comment by HailunTan** [comment]
Hi @sakanaosama, 
Thanks for your reply.

I do not expect to do ANY link extraction on doc type of files. So if the ExtensionReferenceFilters were placed in documentFilters. Then the doc files had been fetched and parsed (with link extraction) already.  

Also, I do not expect to keep any downloaded  HTML files. The link extractions were needed for HTML not the HTML files were not needed to be stored in /downloads folder.
