### ISSUE TITLE
Drupal website - unpublished documents returning an HTTP status of 403 - how to have them deleted

### ISSUE THREAD

**Issue by onixterry** [Norconex/crawlers#984]
I am crawling a website hosted by Drupal and using Norconex 2.9.x.  I am crawling using a sitemap.

When pages are "deleted" they are actually just unpublished in Drupal and the web server returns a 403 unauthorized error instead of a 404.

Is there any way to configure Norconex to treat the 403 as a 404 and send a deletion request to the committer just like a 404 will do?  I haven't found anything that indicates this is possible.  If it's not possible, any suggestions on a workaround, other than asking the server admin to return a 404 status for unpublished pages?

**Comment by ohtwadi** [comment]
One of `<validStatusCodes>` or `<notFoundStatusCodes>` might help.

```xml
<documentFetcher
      class="com.norconex.collector.http.fetch.impl.GenericDocumentFetcher"
      detectContentType="[false|true]" detectCharset="[false|true]">
    <validStatusCodes>(defaults to 200)</validStatusCodes>
    <notFoundStatusCodes>(defaults to 404)</notFoundStatusCodes>
    <headersPrefix>(string to prefix headers)</headersPrefix>
  </documentFetcher>
```

https://opensource.norconex.com/crawlers/web/v2/apidocs/com/norconex/collector/http/fetch/impl/GenericDocumentFetcher.html

Not tested

**Comment by onixterry** [comment]
Yes, this does work.  Thank you.
